{{- if .Values.destinationRule.create -}}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  host: {{- tpl (toYaml .Values.destinationRule.host) . | nindent 4 }}
  {{- with .Values.destinationRule.subsets }}
  subsets:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}