{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.serviceType }}
  selector:
    app: {{ .Values.service.selectorName }}
  ports:
    {{- tpl (toYaml .Values.service.ports) . | nindent 4 }}
{{- end }}